import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {InteractiveBudget,responseBounds,settleResponse,boundedWav} from '../lib/destiny-brain/interactive-budget.js';
import {createBrokerOperations} from '../lib/destiny-brain/interactive-broker.js';
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'private-budget-test-'));t.after(async()=>{assert.equal(path.dirname(root),os.tmpdir());assert.ok(path.basename(root).startsWith('private-budget-test-'));await fs.rm(root,{recursive:true,force:true});});return new InteractiveBudget(root).init();}
const p=()=>({model:'gpt-5.6-sol',max_output_tokens:2400,store:false,stream:false,service_tier:'default',reasoning:{effort:'low'},text:{verbosity:'low'},parallel_tool_calls:false,tools:[],input:[{role:'user',content:'Synthetic hello'}]});
function wav(seconds){const b=Buffer.alloc(44+32000*seconds);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(32000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);return b.toString('base64');}
test('shared queue cannot overspend when Chat and Voice arrive concurrently',async t=>{const b=await fixture(t);let dispatched=0;const call=()=>b.call('mock',3000000,async()=>{dispatched++;return {value:true,settledMicros:3000000,usage:{synthetic:true}};});const results=await Promise.allSettled([call(),call()]);assert.equal(dispatched,1);assert.equal(results[1].status,'rejected');assert.equal(b.status().accountedUsd,3);assert.equal(b.status().halted,'cost_cap');});
test('successful usage is persisted and restart never grants another five dollars',async t=>{const b=await fixture(t);await b.call('mock',1000000,async()=>({value:true,settledMicros:123456,usage:{synthetic:true}}));const reopened=await new InteractiveBudget(b.root).init();assert.equal(reopened.status().accountedUsd,0.123456);assert.equal(reopened.status().remainingUsd,4.876544);});
test('technical failure preserves full uncertainty reservation and blocks every later call',async t=>{const b=await fixture(t);await assert.rejects(b.call('mock',1000000,async()=>{throw Error('synthetic timeout');}));assert.equal(b.status().reservedOrUncertainUsd,1);let called=false;await assert.rejects(b.call('speech',15,async()=>{called=true;}));assert.equal(called,false);assert.equal((await new InteractiveBudget(b.root).init()).status().accountedUsd,1);});
test('crash residue and corrupted negative usage fail closed',async t=>{const b=await fixture(t);b.data.rows=[{id:1,kind:'mock',status:'reserved',reservedMicros:1000000}];await b.save();assert.equal((await new InteractiveBudget(b.root).init()).status().halted,'unfinished_request_usage_uncertain');b.data.rows[0].settledMicros=-1;await b.save();await assert.rejects(new InteractiveBudget(b.root).init(),/integrity/);});
test('bounds reject extra-priced tools, unbounded outputs and malformed usage',()=>{assert.ok(responseBounds(p()).reserve>0);assert.throws(()=>responseBounds({...p(),tools:[{type:'web_search'}]}));assert.throws(()=>responseBounds({...p(),max_output_tokens:10000}));assert.throws(()=>settleResponse(null,responseBounds(p())));assert.throws(()=>settleResponse({input_tokens:999999,output_tokens:1},responseBounds(p())));});
test('PCM duration is proven from canonical bytes, never a browser duration claim',()=>{assert.equal(boundedWav(wav(1)).seconds,1);assert.throws(()=>boundedWav(wav(31)));const b=Buffer.from(wav(1),'base64');b.writeUInt32LE(1,24);assert.throws(()=>boundedWav(b.toString('base64')));});
test('broker model request is fixed to OpenAI and credentials never enter payload or saved results',async t=>{const budget=await fixture(t);let requests=0;const op=createBrokerOperations({apiKey:'synthetic-test-token',budget,fetchImpl:async(url,o)=>{requests++;assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(o.redirect,'error');assert.doesNotMatch(o.body,/synthetic-test-token/);return {ok:true,json:async()=>({status:'completed',output:[],output_text:'Synthetic hello',usage:{input_tokens:100,output_tokens:10}})};}});assert.equal((await op('responses',p())).status,'completed');assert.equal(requests,1);assert.ok(budget.status().accountedUsd<0.01);await assert.rejects(op('write',{method:'sendOwnerChatInvite'}));});
test('bounded transcription and multi-chunk speech share the same ledger without model composition',async t=>{const budget=await fixture(t),urls=[];const op=createBrokerOperations({apiKey:'synthetic-test-token',budget,fetchImpl:async(url,o)=>{urls.push(url);return url.endsWith('transcriptions')?{ok:true,json:async()=>({text:'Synthetic hello',duration:1})}:{ok:true,arrayBuffer:async()=>Buffer.from('synthetic-audio')};}});assert.equal((await op('transcribe',{wav:wav(1)})).text,'Synthetic hello');const speech=await op('speech',{text:'x'.repeat(5000),decisionId:'mock'});assert.equal(speech.clips.length,2);assert.equal(urls.length,3);assert.equal(budget.status().accountedUsd,0.0752);});
test('read broker never exposes message, lead or record services',async t=>{const budget=await fixture(t);let writes=0;const op=createBrokerOperations({apiKey:'synthetic',budget,services:{sendOwnerChatInvite:()=>writes++,checkBothUnits:()=>({'707':true,'1006':false})}});await assert.rejects(op('read',{method:'sendOwnerChatInvite',args:[]}));assert.equal(writes,0);assert.deepEqual(await op('read',{method:'checkBothUnits',args:['2027-01-01','2027-01-04']}),{'707':true,'1006':false});});
